server:
  port: ${APP_PORT}
env:
  SECRET_KEY: ${SECRET_KEY}
  JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
spring:
  datasource:
    driverClassName: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update