server:
  port: ${APP_PORT}
env:
  SECRET_KEY: ${SECRET_KEY}
  JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
  ADM_USER: ${ADM_USER}
  ADM_PASSWORD: ${ADM_PASSWORD}
  EMAIL_TARGET: ${EMAIL_TARGET}

  GCP_CLIENT_ID: ${GCP_CLIENT_ID}
  GCP_SERVICE_ACCOUNT: ${GCP_SERVICE_ACCOUNT}
  GCP_PRIVATE_KEY: ${GCP_PRIVATE_KEY}
  GCP_PRIVATE_KEY_ID: ${GCP_PRIVATE_KEY_ID}
  GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true